spring:
  application:
    name: BookingService
  data:
    mongodb:
      port: 2702
      host: localhost
      database: booking-db
  cloud:
    openfeign:
      client:
        config:
          property:
            url: http://localhost:10000/properties
#          user:
#            url: http://localhost:10002/users

server:
  port: 10001
