spring:
  application:
    name: BookingService
  data:
    mongodb:
      port: 27017
      host: mongo-booking-service
      database: booking-db
  cloud:
    openfeign:
      client:
        config:
          property:
            url: http://property-service:8080/properties
