version: "3.8"

services:
  mongo-property-service:
    container_name: property-service-database
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: property-db
    ports:
      - "2701:27017"

#  property-service:
#    container_name: property-service-application
#    build: ./property-service
#    depends_on:
#      - mongo-property-service
#      - eureka-server
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env

  mongo-booking-service:
    container_name: booking-service-database
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: booking-db
    ports:
      - "2702:27017"

#  booking-service:
#    container_name: booking-service-application
#    build: ./booking-service
#    depends_on:
#      - mongo-booking-service
#      - eureka-server
#    ports:
#      - "8081:8080"
#    env_file:
#      - .env
  
  mongo-user-service:
    container_name: user-service-database
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: user-db
    ports:
      - "2703:27017"
  
#  user-service:
#    container_name: user-service-application
#    build: ./user-service
#    depends_on:
#      - mongo-user-service
#      - eureka-server
#    ports:
#      - "8082:8080"
#    env_file:
#      - .env

  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    ports:
      - "8083:8080"

  gateway-service:
    container_name: gateway-service
    build: ./gateway-service
    depends_on:
      - eureka-server
    ports:
      - "8888:8080"
    env_file:
      - .env
