version: "3.8"

services:
  mongo-property-service:
    container_name: property-service-database
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: property-db
    ports:
      - "2701:27017"

#  property-service:
#    container_name: property-service-application
#    build: ./property-service
#    depends_on:
#      - mongo-property-service
#      - eureka-server
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env

  mongo-booking-service:
    container_name: booking-service-database
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: booking-db
    ports:
      - "2702:27017"

#  booking-service:
#    container_name: booking-service-application
#    build: ./booking-service
#    depends_on:
#      - mongo-booking-service
#      - eureka-server
#    ports:
#      - "8081:8080"
#    env_file:
#      - .env
  
#  user-service:
#    container_name: user-service-application
#    build: ./user-service
#    depends_on:
#      - mongo-user-service
#      - eureka-server
#    ports:
#      - "8082:8080"
#    env_file:
#      - .env

  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    ports:
      - "8083:8080"

#  gateway-service:
#    container_name: gateway-service
#    build: ./gateway-service
#    depends_on:
#      - eureka-server
#      - keycloak_web
#    ports:
#      - "8888:8080"
#    env_file:
#      - .env

  keycloak_web:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 1234

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 10000
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: ./gateway-service/RealEstateRentalPlatform-realm.json
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./gateway-service/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-db
    ports:
      - "10000:8080"

  keycloak-db:
    image: postgres
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
