version: "3.8"

services:
  mongo-property-service:
    container_name: property-service-database
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: property-db
    ports:
      - "2701:27017"

  property-service:
    container_name: property-service-application
    build: ./PropertyService
    ports:
      - "8080:8080"

  mongo-booking-service:
    container_name: booking-service-database
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: booking-db
    ports:
      - "2702:27017"

  booking-service:
    container_name: booking-service-application
    build: ./BookingService
    ports:
      - "8081:8080"
  
  postgres-user-service:
    container_name: user-service-database
    image: postgres
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user-db
