spring:
  application:
    name: PropertyService

  data:
    mongodb:
      port: ${DB_PORT:2701}
      host: ${PROPERTY_DB_HOST:localhost}
      database: property-db

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8083/eureka/}

server:
  port: ${PROPERTY_PORT:8080}
