spring:
  application:
    name: booking-service
  data:
    mongodb:
      port: ${DB_PORT:2702}
      host: ${BOOKING_DB_HOST:localhost}
      database: booking-db
  cloud:
    openfeign:
      client:
        config:
          property:
            url: ${PROPERTY_FEIGN_CLIENT_URL:http://localhost:8080/properties}
          bank-card:
            url: ${BANK_CARD_FEIGN_CLIENT_URL:http://localhost:8082/bankCards}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8083/eureka/}

server:
  port: ${BOOKING_PORT:8081}
