spring:
  application:
    name: EurekaServer

server:
  port: 20000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:20000/eureka

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF