spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:10000/realms/RealEstateRentalPlatform/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:10000/realms/RealEstateRentalPlatform
        registration:
          keycloak:
            provider: keycloak
            client-id: gateway-security
            client-secret: jxQswsT4s4b2AAESaJ0KEHnKPAofTWLw
            authorization-grant-type: authorization_code
            scope: openid

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: property-service-route
          uri: lb://property-service
          predicates:
            - Path=/properties
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/users
        - id: booking-service-route
          uri: lb://booking-service
          predicates:
            - Path=/bookings,/payments

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8083/eureka/}

server:
  port: 8084
logging:
  level:
    org.springframework.security: TRACE
