spring:
  application:
    name: user-service
  data:
    mongodb:
      port: ${DB_PORT:2703}
      host: ${USER_DB_HOST:localhost}
      database: user-db

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8083/eureka/}

server:
  port: ${USER_PORT:8082}
