spring:
  application:
    name: user-service
  r2dbc:
    url: ${KEYCLOAK_POSTGRES_URL:r2dbc:postgresql://localhost:5555/keycloak}
    username: postgres
    password: 1234
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    url: ${KEYCLOAK_LIQUIBASE_POSTGRES_URL:jdbc:postgresql://localhost:5555/keycloak}
    user: postgres
    password: 1234

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8083/eureka/}

server:
  port: 8882

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
