spring:
  application:
    name: UserService
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5555/user-db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

server:
  port: 10002
